### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 35464) exited unexpectedly

### ISSUE THREAD

**Issue by 2022wannarest** [SCLBD/BackdoorBench#40]
Hello, thank you for the thorough summary you provided. I encountered a problem while executing a command; when i executing
 ### python ./attack/badnet.py --yaml_path ../config/attack/prototype/cifar10.yaml --patch_mask_path ../resource/badnet/trigger_image.png 
![image](https://github.com/SCLBD/BackdoorBench/assets/102201152/85ede641-d1ef-495a-ba95-27a82e0df254)

 there might be an infinite loop in the __getattr__ method within bd_dataset_v2.py. I searched online for a solution and found that reducing the number of num_workers could help. I have already adjusted it to 1, but the problem persists. Could you suggest any other possible solutions? 
Thanks!

python ./attack/badnet.py --yaml_path ../config/attack/prototype/cifar10.yaml --patch_mask_path ../resource/badnet/trigger_image.png

**Comment by 2022wannarest** [comment]
the whole output is 
INFO:root:{'amp': False,
 'attack': 'badnet',
 'attack_label_trans': 'all2one',
 'attack_target': 0,
 'batch_size': 128,
 'bd_yaml_path': '../config/attack/badnet/default.yaml',
 'client_optimizer': 'sgd',
 'dataset': 'cifar10',
 'dataset_path': '../data/cifar10',
 'device': 'cuda:0',
 'epochs': 100,
 'frequency_save': 0,
 'img_size': (32, 32, 3),
 'input_channel': 3,
 'input_height': 32,
 'input_width': 32,
 'lr': 0.01,
 'lr_scheduler': 'CosineAnnealingLR',
 'model': 'preactresnet18',
 'non_blocking': True,
 'num_classes': 10,
 'num_workers': 1,
 'patch_mask_path': '../resource/badnet/trigger_image.png',
 'pin_memory': False,
 'pratio': 0.1,
 'prefetch': False,
 'random_seed': 0,
 'save_path': '../record/20240502_021031_badnet__badnet_KoeU',
 'sgd_momentum': 0.9,
 'wd': 0.0005,
 'yaml_path': '../config/attack/prototype/cifar10.yaml'}
2024-05-02:02:10:31 [INFO    ] [prototype.py:127] {'amp': False,
 'attack': 'badnet',
 'attack_label_trans': 'all2one',
 'attack_target': 0,
 'batch_size': 128,
 'bd_yaml_path': '../config/attack/badnet/default.yaml',
 'client_optimizer': 'sgd',
 'dataset': 'cifar10',
 'dataset_path': '../data/cifar10',
 'device': 'cuda:0',
 'epochs': 100,
 'frequency_save': 0,
 'img_size': (32, 32, 3),
 'input_channel': 3,
 'input_height': 32,
 'input_width': 32,
 'lr': 0.01,
 'lr_scheduler': 'CosineAnnealingLR',
 'model': 'preactresnet18',
 'non_blocking': True,
 'num_classes': 10,
 'num_workers': 1,
 'patch_mask_path': '../resource/badnet/trigger_image.png',
 'pin_memory': False,
 'pratio': 0.1,
 'prefetch': False,
 'random_seed': 0,
 'save_path': '../record/20240502_021031_badnet__badnet_KoeU',
 'sgd_momentum': 0.9,
 'wd': 0.0005,
 'yaml_path': '../config/attack/prototype/cifar10.yaml'}
DEBUG:root:Only INFO or above level log will show in cmd. DEBUG level log only will show in log file.
DEBUG:root:{'git hash': None,
 'last 3 log': 'commit cfeeed27ab53f985ca5b6271c71bceea2e51a380\n'
               'Author: mdzhang <55868217+mdzhangst@users.noreply.github.com>\n'
               'Date:   Sat Apr 20 11:07:23 2024 +0800\n'
               '\n'
               '    Update README.md\n'
               '\n'
               'commit 06ad2948fea59ed6cfcdfc6de8fe851fad3496a1\n'
               'Author: Hongrui CHEN '
               '<75762846+CHR-ray@users.noreply.github.com>\n'
               'Date:   Mon Apr 8 14:44:00 2024 +0800\n'
               '\n'
               '    Update README.md\n'
               '\n'
               'commit a7cc9b72bebc55e5a05c056596b16e6ecc907c39\n'
               'Author: Shawkui <shaokui.w@gmail.com>\n'
               'Date:   Fri Feb 2 21:45:28 2024 +0800\n'
               '\n'
               '    Add SAU Configs',
 'status': 'On branch main\n'
           "Your branch is up to date with 'origin/main'.\n"
           '\n'
           'Changes not staged for commit:\n'
           '  (use "git add <file>..." to update what will be committed)\n'
           '  (use "git restore <file>..." to discard changes in working '
           'directory)\n'
           '\tmodified:   badnet.py\n'
           '\tmodified:   prototype.py\n'
           '\tmodified:   ../config/attack/prototype/cifar10.yaml\n'
           '\tmodified:   ../sh/install.sh\n'
           '\tmodified:   ../utils/aggregate_block/save_path_generate.py\n'
           '\tmodified:   ../utils/trainer_cls.py\n'
           '\n'
           'Untracked files:\n'
           '  (use "git add <file>..." to include in what will be committed)\n'
           '\tmodels/\n'
           '\tutils/\n'
           '\t../badnet.py\n'
           '\t../prototype.py\n'
           '\t../sh/requirement.txt\n'
           '\t"../\\346\\214\\207\\344\\273\\244.txt"\n'
           '\n'
           'no changes added to commit (use "git add" and/or "git commit -a")'}
prepare : Namespace(amp=False, attack='badnet', attack_label_trans='all2one', attack_target=0, batch_size=128, bd_yaml_path='../config/attack/badnet/default.yaml', client_optimizer='sgd', dataset='cifar10', dataset_path='../data/cifar10', device='cuda:0', epochs=100, frequency_save=0, img_size=(32, 32, 3), input_channel=3, input_height=32, input_width=32, lr=0.01, lr_scheduler='CosineAnnealingLR', model='preactresnet18', non_blocking=True, num_classes=10, num_workers=1, patch_mask_path='../resource/badnet/trigger_image.png', pin_memory=False, pratio=0.1, prefetch=False, random_seed=0, save_path='../record/20240502_021031_badnet__badnet_KoeU', sgd_momentum=0.9, wd=0.0005, yaml_path='../config/attack/prototype/cifar10.yaml')
INFO:root:stage1 start
2024-05-02:02:10:31 [INFO    ] [badnet.py:82] stage1 start
Files already downloaded and verified
Files already downloaded and verified
DEBUG:root:dataset_and_transform_generate done
DEBUG:root:Not DatasetFolder or ImageFolder, so iter through
DEBUG:root:Not DatasetFolder or ImageFolder, so iter through
DEBUG:root:Reminder: plz note that if p_num or pratio exceed the number of possible candidate samples
 then only maximum number of samples will be applied
DEBUG:root:Reminder: priority p_num > pratio, and choosing fix number of sample is prefered if possible
INFO:root:poison num:5000.0,real pratio:0.1
2024-05-02:02:10:33 [INFO    ] [backdoor_generate_poison_index.py:61] poison num:5000.0,real pratio:0.1
DEBUG:root:poison train idx is saved
INFO:root:save file format is .png
2024-05-02:02:10:33 [INFO    ] [bd_dataset_v2.py:133] save file format is .png
prepro_backdoor: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [00:07<00:00, 6503.12it/s]
DEBUG:root:Reminder: plz note that if p_num or pratio exceed the number of possible candidate samples
 then only maximum number of samples will be applied
DEBUG:root:Reminder: priority p_num > pratio, and choosing fix number of sample is prefered if possible
INFO:root:poison num:9000.0,real pratio:0.9
2024-05-02:02:10:41 [INFO    ] [backdoor_generate_poison_index.py:61] poison num:9000.0,real pratio:0.9
INFO:root:save file format is .png
2024-05-02:02:10:41 [INFO    ] [bd_dataset_v2.py:133] save file format is .png
prepro_backdoor: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10000/10000 [00:13<00:00, 724.02it/s]
INFO:root:stage2 start
2024-05-02:02:10:55 [INFO    ] [badnet.py:164] stage2 start
DEBUG:root:image_size ONLY apply for vit!!!
If you use vit make sure you set the image size!
DEBUG:root:Make sure you want PreActResNet18, which is NOT resnet18.
DEBUG:root:This class REQUIRE bd dataset to implement overwrite methods. This is NOT a general class for all cls task.
INFO:root:Do NOT set the settings/parameters attr manually after you start training!
You may break the relationship between them.
2024-05-02:02:10:55 [INFO    ] [trainer_cls.py:954] Do NOT set the settings/parameters attr manually after you start training!
You may break the relationship between them.
current working directory: C:\Users\Brian\Desktop\nycu\first_year\Backdoor\BackdoorBench\attack
current python path: ['C:\\Users\\Brian\\Desktop\\nycu\\first_year\\Backdoor\\BackdoorBench\\attack', 'C:\\Users\\Brian\\anaconda3\\envs\\backdoorbench\\python38.zip', 'C:\\Users\\Brian\\anaconda3\\envs\\backdoorbench\\DLLs', 'C:\\Users\\Brian\\anaconda3\\envs\\backdoorbench\\lib', 'C:\\Users\\Brian\\anaconda3\\envs\\backdoorbench', 'C:\\Users\\Brian\\anaconda3\\envs\\backdoorbench\\lib\\site-packages', '../', '../', '../../', '../../', '../', '../../', '../', '../', '../../', '../../']
current working directory: C:\Users\Brian\Desktop\nycu\first_year\Backdoor\BackdoorBench\attack
current python path: ['C:\\Users\\Brian\\Desktop\\nycu\\first_year\\Backdoor\\BackdoorBench\\attack', 'C:\\Users\\Brian\\anaconda3\\envs\\backdoorbench\\python38.zip', 'C:\\Users\\Brian\\anaconda3\\envs\\backdoorbench\\DLLs', 'C:\\Users\\Brian\\anaconda3\\envs\\backdoorbench\\lib', 'C:\\Users\\Brian\\anaconda3\\envs\\backdoorbench', 'C:\\Users\\Brian\\anaconda3\\envs\\backdoorbench\\lib\\site-packages', '../', '../', '../../', '../../', '../', '../../', '../', '../', '../../', '../../']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
INFO:root:('epoch_now:0, '
 'batch_now:0self.amp:False,self.criterion:CrossEntropyLoss(),self.optimizer:SGD '
 '(\n'
 'Parameter Group 0\n'
 '    dampening: 0\n'
 '    differentiable: False\n'
 '    foreach: None\n'
 '    initial_lr: 0.01\n'
 '    lr: 0.01\n'
 '    maximize: False\n'
 '    momentum: 0.9\n'
 '    nesterov: False\n'
 '    weight_decay: 0.0005\n'
 "),self.scheduler:{'T_max': 100, 'eta_min': 0, 'base_lrs': [0.01], "
 "'last_epoch': 0, 'verbose': False, '_step_count': 1, "
 "'_get_lr_called_within_step': False, '_last_lr': [0.01]},self.scaler:{})")
2024-05-02:02:10:58 [INFO    ] [trainer_cls.py:1012] ('epoch_now:0, '
 'batch_now:0self.amp:False,self.criterion:CrossEntropyLoss(),self.optimizer:SGD '
 '(\n'
 'Parameter Group 0\n'
 '    dampening: 0\n'
 '    differentiable: False\n'
 '    foreach: None\n'
 '    initial_lr: 0.01\n'
 '    lr: 0.01\n'
 '    maximize: False\n'
 '    momentum: 0.9\n'
 '    nesterov: False\n'
 '    weight_decay: 0.0005\n'
 "),self.scheduler:{'T_max': 100, 'eta_min': 0, 'base_lrs': [0.01], "
 "'last_epoch': 0, 'verbose': False, '_step_count': 1, "
 "'_get_lr_called_within_step': False, '_last_lr': [0.01]},self.scaler:{})")
  File "C:\Users\Brian\anaconda3\envs\backdoorbench\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Brian\anaconda3\envs\backdoorbench\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\Brian\Desktop\nycu\first_year\Backdoor\BackdoorBench\attack\utils\bd_dataset_v2.py", line 94, in __getattr__
    return getattr(self.wrapped_dataset, attr)
  File "C:\Users\Brian\Desktop\nycu\first_year\Backdoor\BackdoorBench\attack\utils\bd_dataset_v2.py", line 94, in __getattr__
    return getattr(self.wrapped_dataset, attr)
  File "C:\Users\Brian\Desktop\nycu\first_year\Backdoor\BackdoorBench\attack\utils\bd_dataset_v2.py", line 94, in __getattr__
    return getattr(self.wrapped_dataset, attr)
  [Previous line repeated 993 more times]
RecursionError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "C:\Users\Brian\anaconda3\envs\backdoorbench\lib\site-packages\torch\utils\data\dataloader.py", line 1120, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\Brian\anaconda3\envs\backdoorbench\lib\multiprocessing\queues.py", line 108, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./attack/badnet.py", line 252, in <module>
    attack.stage2_training()
  File "./attack/badnet.py", line 201, in stage2_training
    trainer.train_with_test_each_epoch_on_mix(
  File "C:\Users\Brian\Desktop\nycu\first_year\Backdoor\BackdoorBench\attack\utils\trainer_cls.py", line 1912, in train_with_test_each_epoch_on_mix
    train_epoch_original_targets_list = self.train_one_epoch_on_mix(verbose=1)
  File "C:\Users\Brian\Desktop\nycu\first_year\Backdoor\BackdoorBench\attack\utils\trainer_cls.py", line 1762, in train_one_epoch_on_mix
    x, labels, original_index, poison_indicator, original_targets  = self.get_one_batch()
  File "C:\Users\Brian\Desktop\nycu\first_year\Backdoor\BackdoorBench\attack\utils\trainer_cls.py", line 1121, in get_one_batch
    return self.train_iter.__next__()
  File "C:\Users\Brian\anaconda3\envs\backdoorbench\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "C:\Users\Brian\anaconda3\envs\backdoorbench\lib\site-packages\torch\utils\data\dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "C:\Users\Brian\anaconda3\envs\backdoorbench\lib\site-packages\torch\utils\data\dataloader.py", line 1282, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\Brian\anaconda3\envs\backdoorbench\lib\site-packages\torch\utils\data\dataloader.py", line 1133, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 35464) exited unexpectedly

**Comment by 2022wannarest** [comment]
set num_workers = 0 can solve the problem
